import type {Metadata} from 'next'
import {Rubik} from 'next/font/google'
import './globals.css'
import {ToastContainer} from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import NavBar from './components/navbar/navbar'

const rubik = Rubik({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${rubik.className}`}>
				<NavBar />
				<ToastContainer />
				<div className='relative top-16'>{children}</div>
			</body>
		</html>
	)
}
